/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant1 = new Restaurant("restaurant1", 3,4);
        restaurant1.addReview("good review", "author1", 3);
        System.out.println(restaurant1.toString());
//
        Restaurant restaurant2 = new Restaurant("restaurant2", 3,10);
        restaurant2.addReview("poor review", "author2", 1);
        System.out.println(restaurant2.toString());
//
//        Restaurant restaurant3 = new Restaurant("restaurant3", 3,7);
//        restaurant3.addReview("excellent review", "author1", 4);
//        System.out.println(restaurant3.toString());

//        Review review = new Review("restaurant3","excellent review", "author1", 4 );
//        System.out.println(review.toString());


    }
}


