/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
//        Restaurant restaurant1 = new Restaurant("restaurant1", 8,4);
//        restaurant1.addReview("good review", "author1", 3);
//        String result =restaurant1.toString();


        Restaurant restaurant1 = new Restaurant("restaurant1", 3,4);
        restaurant1.addReview("good review", "author1", 3);
        String result =restaurant1.toString();
        
        String expected = "restaurant info... name: restaurant1 number of stars 3 price 4\n" +
                " Review: Review info: good review author: author1 number of stars: 3";

        assertEquals("an error occurred", expected, result);
        
        

    }
}
